matrix:
  include:
  
    # WebApp
    - language: python
      install:
        - pip install -r WebApp/requirements.txt
      before_script:
        - cd WebApp 
      script:
        - python manage.py makemigrations WebApp
        - python manage.py migrate WebApp
        - python manage.py test
       
    - language: dart
      dist: xenial
      branches: 
        only:
        - mobileDev
      addons:
          apt:
              packages:
                  - lib32stdc++6
      install:
        - git clone https://github.com/flutter/flutter.git -b stable
        - ./flutter/bin/flutter doctor
        - gem install coveralls-lcov
      before_script: 
        - cd /Mobile/lib
      script:
        - ./flutter/bin/flutter test --coverage
      after_success:
        - coveralls-lcov coverage/lcov.info
      cache:
          directories:
              - $HOME/.pub-cache
