matrix:
  include:
  
    # WebApp
    - language: python
      install:
        - pip install -r WebApp/requirements.txt
      before_script:
        - cd WebApp 
      script:
        - python manage.py makemigrations WebApp
        - python manage.py migrate WebApp
        - python manage.py test

    # Mobile
        language: dart
        before_script:
            - git clone https://github.com/flutter/flutter.git -b stable
            - ./flutter/bin/flutter doctor
        script:
            - ./flutter/bin/flutter test
