matrix:
  include:
  
    # WebApp
    - language: python
      install:
        - pip install -r WebApp/requirements.txt
      before_script:
        - cd WebApp 
      script:
        - python manage.py makemigrations
        - python manage.py migrate
        - python manage.py test
