# Generated by Django 3.0.3 on 2020-03-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='id',
        ),
        migrations.AlterField(
            model_name='station',
            name='ip',
            field=models.GenericIPAddressField(primary_key=True, protocol='IPv4', serialize=False),
        ),
    ]
