# Generated by Django 3.0.3 on 2020-03-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_auto_20200310_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='station',
            name='ip',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
    ]
