# Generated by Django 3.0.3 on 2020-03-14 20:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_auto_20200314_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='ip',
        ),
        migrations.AlterField(
            model_name='station',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
