# Generated by Django 3.0.3 on 2020-03-22 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_auto_20200314_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='id',
            new_name='uuid',
        ),
    ]
