# Generated by Django 3.0.3 on 2020-03-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_station_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='ip',
            field=models.GenericIPAddressField(default=''),
        ),
    ]
