# Generated by Django 3.0.3 on 2020-03-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_auto_20200324_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='ip',
            field=models.GenericIPAddressField(blank=True, default='', null=True),
        ),
    ]
